import {
  User,
  LitsUser,
  StudentRosterRecord,
  EventItem,
  Registration,
  AttendanceRecord,
  EvaluationForm,
  EvaluationResponse,
  AuditLog,
  SystemNotification,
} from "./types";

export const BOOTSTRAP_ADMIN_EMAIL = "tanyafontanilla7@gmail.com";
export const STUDENT_EMAIL_DOMAIN = "@acdeducation.com";

export const INITIAL_STUDENT_ROSTER: StudentRosterRecord[] = [
  {
    id: "ROSTER-001",
    email: "juan.delacruz@acdeducation.com",
    studentId: "2024-BSIT-0145",
    name: "Juan Dela Cruz",
    course: "BSIT",
    yearLevel: "3rd Year",
    isActive: true,
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "ROSTER-002",
    email: "maria.santos@acdeducation.com",
    studentId: "2024-BSIT-0199",
    name: "Maria Santos",
    course: "BSIT",
    yearLevel: "2nd Year",
    isActive: true,
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "ROSTER-003",
    email: "mark.reyes@acdeducation.com",
    studentId: "2024-BSCS-0042",
    name: "Mark Anthony Reyes",
    course: "BSCS",
    yearLevel: "4th Year",
    isActive: true,
    createdAt: "2026-08-01T08:00:00Z",
  },
];

export const INITIAL_LITS_USERS: LitsUser[] = [
  {
    id: "LITS-001",
    email: "lits.officer@acd.edu.ph",
    name: "Carlos Mendoza",
    department: "LITS Technical & Events Committee",
    notes: "Lead Coordinator for Fall 2026 events",
    isActive: true,
    authorizedBy: BOOTSTRAP_ADMIN_EMAIL,
    authorizedAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-01T08:00:00Z",
  },
  {
    id: "LITS-002",
    email: "sarah.lead@acd.edu.ph",
    name: "Sarah Jenkins",
    department: "LITS Logistics & Membership",
    notes: "Attendance Verification Officer",
    isActive: true,
    authorizedBy: BOOTSTRAP_ADMIN_EMAIL,
    authorizedAt: "2026-09-05T08:00:00Z",
    updatedAt: "2026-09-05T08:00:00Z",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "USR-ADM-001",
    name: "Tanya Fontanilla",
    email: BOOTSTRAP_ADMIN_EMAIL,
    role: "ADMIN",
    isBootstrap: true,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&q=80",
  },
  {
    id: "USR-LITS-001",
    name: "Carlos Mendoza",
    email: "lits.officer@acd.edu.ph",
    role: "LITS",
    department: "LITS Technical & Events Committee",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80",
  },
  {
    id: "USR-STU-001",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@acdeducation.com",
    role: "STUDENT",
    studentId: "2024-BSIT-0145",
    course: "BSIT",
    yearLevel: "3rd Year",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
  },
  {
    id: "USR-STU-002",
    name: "Maria Santos",
    email: "maria.santos@acdeducation.com",
    role: "STUDENT",
    studentId: "2024-BSIT-0199",
    course: "BSIT",
    yearLevel: "2nd Year",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80",
  },
];

const TODAY = new Date().toISOString().split("T")[0];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: "EVT-001",
    title: "LITS AI Build 2026: Next-Gen DevCon",
    description:
      "Official annual tech conference by the League of Information Technology Students. Deep dive into modern web architectures, edge computing, and hands-on system building.",
    bannerImage:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    venue: "IT Building Auditorium, 4th Floor",
    eventDate: TODAY,
    startTime: "09:00",
    endTime: "17:00",
    registrationOpens: `${TODAY}T00:00:00Z`,
    registrationCloses: `${TODAY}T23:59:59Z`,
    attendanceOpens: "08:30",
    attendanceCloses: "17:30",
    maxParticipants: 100,
    currentParticipants: 88,
    eligibility: {
      type: "course_restricted",
      allowedCourses: ["BSIT", "BSCS", "BSIS"],
    },
    status: "ONGOING",
    createdBy: "lits.officer@acd.edu.ph",
    createdAt: "2026-09-20T08:00:00Z",
    updatedAt: "2026-09-28T14:30:00Z",
  },
  {
    id: "EVT-002",
    title: "Cybersecurity & Defense Symposium",
    description:
      "Hands-on workshop exploring web vulnerability analysis, ethical penetration testing techniques, and institutional security posture.",
    bannerImage:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
    venue: "Multimedia Room 201 & Lab 4",
    eventDate: "2026-10-05",
    startTime: "13:00",
    endTime: "16:30",
    registrationOpens: "2026-09-25T00:00:00Z",
    registrationCloses: "2026-10-04T23:59:59Z",
    attendanceOpens: "12:30",
    attendanceCloses: "17:00",
    maxParticipants: 60,
    currentParticipants: 42,
    eligibility: {
      type: "open",
    },
    status: "PUBLISHED",
    createdBy: "lits.officer@acd.edu.ph",
    createdAt: "2026-09-22T10:00:00Z",
    updatedAt: "2026-09-25T09:00:00Z",
  },
  {
    id: "EVT-003",
    title: "LITS CodeCamp & Algorithmic Challenge",
    description:
      "A fast-paced collaborative programming challenge tackling data structures and real-world system optimization.",
    bannerImage:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
    venue: "CS Computer Lab 1 & 2",
    eventDate: "2026-09-15",
    startTime: "10:00",
    endTime: "15:00",
    registrationOpens: "2026-09-01T00:00:00Z",
    registrationCloses: "2026-09-14T23:59:59Z",
    attendanceOpens: "09:30",
    attendanceCloses: "15:30",
    maxParticipants: 50,
    currentParticipants: 50,
    eligibility: {
      type: "open",
    },
    status: "COMPLETED",
    createdBy: "lits.officer@acd.edu.ph",
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-16T10:00:00Z",
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: "REG-2026-0145",
    eventId: "EVT-001",
    studentId: "2024-BSIT-0145",
    studentName: "Juan Dela Cruz",
    studentEmail: "juan.delacruz@acdeducation.com",
    course: "BSIT",
    yearLevel: "3rd Year",
    contactNumber: "+63 917 123 4567",
    qrToken: "QUESTLOG:REG:REG-2026-0145:EVT-001:8f9a2b",
    registeredAt: "2026-09-28T09:30:00Z",
    status: "CONFIRMED",
  },
  {
    id: "REG-2026-0199",
    eventId: "EVT-001",
    studentId: "2024-BSIT-0199",
    studentName: "Maria Santos",
    studentEmail: "maria.santos@acdeducation.com",
    course: "BSIT",
    yearLevel: "2nd Year",
    contactNumber: "+63 918 987 6543",
    qrToken: "QUESTLOG:REG:REG-2026-0199:EVT-001:3e7c1d",
    registeredAt: "2026-09-28T10:15:00Z",
    status: "CONFIRMED",
  },
  {
    id: "REG-2026-0301",
    eventId: "EVT-001",
    studentId: "2024-BSCS-0042",
    studentName: "Mark Anthony Reyes",
    studentEmail: "mark.reyes@acdeducation.com",
    course: "BSCS",
    yearLevel: "4th Year",
    contactNumber: "+63 919 555 1212",
    qrToken: "QUESTLOG:REG:REG-2026-0301:EVT-001:99a14c",
    registeredAt: "2026-09-28T11:00:00Z",
    status: "CONFIRMED",
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "ATT-2026-0145",
    registrationId: "REG-2026-0145",
    eventId: "EVT-001",
    studentId: "2024-BSIT-0145",
    studentName: "Juan Dela Cruz",
    studentEmail: "juan.delacruz@acdeducation.com",
    course: "BSIT",
    yearLevel: "3rd Year",
    checkInTimestamp: `${TODAY}T09:12:35Z`,
    checkedInByOfficerId: "USR-LITS-001",
    checkedInByOfficerName: "Carlos Mendoza (LITS)",
    photoStatus: "NONE",
    verificationStatus: "CHECKED_IN",
    evaluationUnlocked: false,
    createdAt: `${TODAY}T09:12:35Z`,
    updatedAt: `${TODAY}T09:12:35Z`,
  },
  {
    id: "ATT-2026-0199",
    registrationId: "REG-2026-0199",
    eventId: "EVT-001",
    studentId: "2024-BSIT-0199",
    studentName: "Maria Santos",
    studentEmail: "maria.santos@acdeducation.com",
    course: "BSIT",
    yearLevel: "2nd Year",
    checkInTimestamp: `${TODAY}T09:05:10Z`,
    checkedInByOfficerId: "USR-LITS-001",
    checkedInByOfficerName: "Carlos Mendoza (LITS)",
    photoUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=600&q=80",
    photoStatus: "SUBMITTED",
    photoTimestamp: `${TODAY}T09:08:42Z`,
    photoUploadTimestamp: `${TODAY}T09:09:15Z`,
    photoTimestampValid: true,
    photoTimestampValidationNotes: "Photo timestamp verified within official event window (08:30 - 17:30).",
    verificationStatus: "UNDER_REVIEW",
    evaluationUnlocked: false,
    createdAt: `${TODAY}T09:05:10Z`,
    updatedAt: `${TODAY}T09:09:15Z`,
  },
  {
    id: "ATT-2026-0301",
    registrationId: "REG-2026-0301",
    eventId: "EVT-001",
    studentId: "2024-BSCS-0042",
    studentName: "Mark Anthony Reyes",
    studentEmail: "mark.reyes@acdeducation.com",
    course: "BSCS",
    yearLevel: "4th Year",
    checkInTimestamp: `${TODAY}T08:58:20Z`,
    checkedInByOfficerId: "USR-LITS-001",
    checkedInByOfficerName: "Carlos Mendoza (LITS)",
    photoUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=600&q=80",
    photoStatus: "VERIFIED",
    photoTimestamp: `${TODAY}T09:02:18Z`,
    photoUploadTimestamp: `${TODAY}T09:03:00Z`,
    photoTimestampValid: true,
    photoTimestampValidationNotes: "Photo verified and matched with auditorium presence.",
    verificationStatus: "VERIFIED",
    verifiedByOfficerId: "USR-LITS-001",
    verifiedByOfficerName: "Carlos Mendoza (LITS)",
    verifiedAt: `${TODAY}T09:15:00Z`,
    evaluationUnlocked: true,
    createdAt: `${TODAY}T08:58:20Z`,
    updatedAt: `${TODAY}T09:15:00Z`,
  },
];

export const INITIAL_EVALUATIONS: EvaluationForm[] = [
  {
    id: "EVAL-EVT-001",
    eventId: "EVT-001",
    title: "LITS AI Build 2026 — Official Participant Evaluation",
    description:
      "Thank you for attending LITS AI Build 2026. Please complete this evaluation to help us improve future organization, technical workshops, and venue preparations.",
    isPublished: true,
    allowEdit: false,
    questions: [
      {
        id: "Q1",
        questionText: "How would you rate the overall organization and event flow?",
        questionType: "rating",
        required: true,
      },
      {
        id: "Q2",
        questionText: "How relevant and useful were the speaker topics and technical demos?",
        questionType: "rating",
        required: true,
      },
      {
        id: "Q3",
        questionText: "Which segment did you find the most valuable?",
        questionType: "multiple_choice",
        options: [
          "Keynote & Modern Web Tech",
          "Live Hands-on Coding Session",
          "Q&A and Career Networking",
          "Student Project Showcase",
        ],
        required: true,
      },
      {
        id: "Q4",
        questionText: "What aspects of the event could be improved for next year?",
        questionType: "short_answer",
        required: false,
      },
      {
        id: "Q5",
        questionText: "Any other feedback or suggestions for the LITS Officers?",
        questionType: "long_answer",
        required: false,
      },
    ],
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-28T12:00:00Z",
  },
];

export const INITIAL_EVALUATION_RESPONSES: EvaluationResponse[] = [
  {
    id: "RESP-001",
    formId: "EVAL-EVT-001",
    eventId: "EVT-001",
    studentId: "2024-BSCS-0042",
    studentName: "Mark Anthony Reyes",
    answers: [
      {
        questionId: "Q1",
        questionText: "How would you rate the overall organization and event flow?",
        value: 5,
      },
      {
        questionId: "Q2",
        questionText: "How relevant and useful were the speaker topics and technical demos?",
        value: 5,
      },
      {
        questionId: "Q3",
        questionText: "Which segment did you find the most valuable?",
        value: "Live Hands-on Coding Session",
      },
      {
        questionId: "Q4",
        questionText: "What aspects of the event could be improved for next year?",
        value: "Provide power extension cords at all auditorium seating rows.",
      },
      {
        questionId: "Q5",
        questionText: "Any other feedback or suggestions for the LITS Officers?",
        value: "The QR check-in and photo verification system is super seamless and organized! Great job LITS!",
      },
    ],
    submittedAt: `${TODAY}T09:20:00Z`,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "LOG-001",
    who: "Tanya Fontanilla (Admin)",
    whoRole: "ADMIN",
    what: "BOOTSTRAP_SYSTEM",
    when: "2026-09-01T08:00:00Z",
    target: "SYSTEM",
    result: "SUCCESS",
    details: "Bootstrap admin initialized for tanyafontanilla7@gmail.com",
  },
  {
    id: "LOG-002",
    who: "Tanya Fontanilla (Admin)",
    whoRole: "ADMIN",
    what: "AUTHORIZE_LITS_USER",
    when: "2026-09-01T08:05:00Z",
    target: "lits.officer@acd.edu.ph",
    result: "SUCCESS",
    details: "Authorized Carlos Mendoza as active LITS Officer",
  },
  {
    id: "LOG-003",
    who: "Carlos Mendoza (LITS)",
    whoRole: "LITS",
    what: "PUBLISH_EVENT",
    when: "2026-09-25T09:00:00Z",
    target: "EVT-001 (LITS AI Build 2026)",
    result: "SUCCESS",
    details: "Event published with registration capacity of 100 participants.",
  },
  {
    id: "LOG-004",
    who: "Juan Dela Cruz",
    whoRole: "STUDENT",
    what: "REGISTER_EVENT",
    when: "2026-09-28T09:30:00Z",
    target: "EVT-001 / REG-2026-0145",
    result: "SUCCESS",
    details: "Student registration created and unique QR token issued.",
  },
  {
    id: "LOG-005",
    who: "Carlos Mendoza (LITS)",
    whoRole: "LITS",
    what: "SCAN_QR",
    when: `${TODAY}T09:12:35Z`,
    target: "REG-2026-0145 (Juan Dela Cruz)",
    result: "SUCCESS",
    details: "QR check-in validated against active attendance window. Server timestamp recorded.",
  },
  {
    id: "LOG-006",
    who: "Maria Santos",
    whoRole: "STUDENT",
    what: "UPLOAD_PHOTO",
    when: `${TODAY}T09:09:15Z`,
    target: "ATT-2026-0199",
    result: "SUCCESS",
    details: "Submitted attendance verification photo with timestamp validation within window.",
  },
  {
    id: "LOG-007",
    who: "Carlos Mendoza (LITS)",
    whoRole: "LITS",
    what: "VERIFY_ATTENDANCE",
    when: `${TODAY}T09:15:00Z`,
    target: "ATT-2026-0301 (Mark Anthony Reyes)",
    result: "SUCCESS",
    details: "Photo approved. Attendance confirmed. Evaluation automatically unlocked.",
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: "NOTIF-001",
    userId: "USR-STU-001",
    userEmail: "juan.delacruz@acdeducation.com",
    title: "Registration Confirmed",
    message: "You are registered for LITS AI Build 2026. Your QR code is ready.",
    type: "success",
    timestamp: "2026-09-28T09:30:00Z",
    read: true,
    link: "/student/registrations/REG-2026-0145/qr",
  },
  {
    id: "NOTIF-002",
    userId: "USR-STU-001",
    userEmail: "juan.delacruz@acdeducation.com",
    title: "QR Scanned — Photo Required",
    message: "Your QR check-in was scanned! Upload your verification photo now.",
    type: "warning",
    timestamp: `${TODAY}T09:12:35Z`,
    read: false,
    link: "/student/attendance/ATT-2026-0145/photo",
  },
  {
    id: "NOTIF-003",
    userId: "USR-LITS-001",
    userEmail: "lits.officer@acd.edu.ph",
    title: "New Photo Submission",
    message: "Maria Santos submitted an attendance photo awaiting verification.",
    type: "info",
    timestamp: `${TODAY}T09:09:15Z`,
    read: false,
    link: "/lits/verification",
  },
];
